### ISSUE TITLE
Stopped working a few days ago

### ISSUE THREAD

**Issue by domhaas** [danielpotthast/mvg#4]
Got this issue since a few days ago:

```
Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:724
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 17:34:12 (2 Vorkommnisse)
Zuletzt protokolliert: 17:34:12

mvg: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 724, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mvg/sensor.py", line 132, in update
    self.data.update()
  File "/config/custom_components/mvg/sensor.py", line 178, in update
    _departures = self.mvg.departures(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/mvg/mvgapi.py", line 408, in departures
    return asyncio.run(self.departures_async(self.station_id, limit, offset, transport_types))
                                             ^^^^^^^^^^^^^^^
AttributeError: 'MvgApi' object has no attribute 'station_id'. Did you mean: 'station'?
```

**Comment by hendrikma** [comment]
Jep, bei mir genau dasselbe. Ist seit dem letzten Update von "Home Assistant Core" so. 

Mir ist nicht klar was das Update verändert hat, denn auch die [genutzte Python-API](https://pypi.org/project/mvg/) wurde nicht verändert in den letzten Monaten.

Auch die MVG-Api scheint an dieser Stelle weiterhin zu funktionieren:
[Abfrage für "Rosenheimer Platz"](https://www.mvg.de/api/fib/v2/location?query=Rosenheimer%20Platz)

**Comment by danielpotthast** [comment]
Could you please test the current unstable build via HACS? This fixed the issue for me.

**Comment by rosch100** [comment]
Fixed it for me as well!

**Comment by domhaas** [comment]
> Could you please test the current unstable build via HACS? This fixed the issue for me.

With 1.1.0-beta.3 everything seems to be working again. Thanks!

**Comment by danielpotthast** [comment]
I’ve published the release. Thanks for reporting it. :)
